INSERT INTO Livre ( titre, dateApparition, editeur, genre, codeClassification, dureeMaxPret, ISBN, resume, langue, contributeur, exemplaires ) VALUES 
('Le Seigneur des Anneaux : La Communauté de l Anneau', '2001-12-19', 'Christian Bourgois', 'Fantasy', 2, 14, '9782266121029', 'Un jeune hobbit du nom de Frodo Baggins hérite d un anneau magique et entreprend un voyage périlleux pour le détruire.', 'français', '{"auteur": [{"nom": "J.R.R.", "prenom": "Tolkien","dateNaissance": "03/01/1892", "nationalite":"britannique"}]}', '[{"id": 4, "etat": "Neuf", "disponible": true}, {"id": 5, "etat": "Bon", "disponible": true}, {"id": 6, "etat": "Abime", "disponible": true}]' ),
('Les Misérables', '1862-01-14', 'A. Lacroix, Verboeckhoven & Cie', 'Roman Historique', 3, 20, '9782266116131', 'L histoire épique de Jean Valjean, un ancien bagnard, et de son parcours pour la rédemption dans la France du XIXe siècle.', 'français', '{"auteur": [{"nom": "Victor", "prenom": "Hugo","dateNaissance": "26/02/1802", "nationalite":"française"}]}', '[{"id": 7, "etat": "Neuf", "disponible": true}, {"id": 8, "etat": "Bon", "disponible": true}, {"id": 9, "etat": "Abime", "disponible": true}]' ),
('Le Petit Prince', '1943-04-06', 'Gallimard', 'Conte philosophique', 4, 8, '9782070408506', 'Les aventures d un jeune prince qui voyage entre différentes planètes, découvrant des leçons de vie.', 'français', '{"auteur": [{"nom": "Antoine", "prenom": "de Saint-Exupéry","dateNaissance": "29/06/1900", "nationalite":"française"}]}', '[{"id": 10, "etat": "Neuf", "disponible": true}, {"id": 11, "etat": "Bon", "disponible": true}, {"id": 12, "etat": "Abime", "disponible": true}]' );

INSERT INTO Film ( titre, dateApparition, editeur, genre, codeClassification, dureeMaxPret, langue, length, synopsis, contributeur, exemplaires ) VALUES
('Le Seigneur des Anneaux : La Communauté de l Anneau', '2001-12-19', 'Warner Bros.', 'Fantasy', 2, 14, 'Français', 178, 'Un jeune hobbit du nom de Frodo Baggins hérite d un anneau magique et entreprend un voyage périlleux pour le détruire.', '{"acteur": [{"nom": "Elijah", "prenom": "Wood", "dateNaissance": "28/01/1981", "nationalite": "américaine"}], "realisateur": [{"nom": "Peter", "prenom": "Jackson", "dateNaissance": "31/10/1961", "nationalite": "néo-zélandaise"}]}', '[{"id": 4, "etat": "Neuf", "disponible": true}, {"id": 5, "etat": "Bon", "disponible": true}, {"id": 6, "etat": "Abime", "disponible": true}]' ),
('Inception', '2010-07-14', 'Warner Bros.', 'Science-Fiction', 3, 12, 'Français', 148, 'Dom Cobb, un voleur expérimenté, est capable d entrer dans les rêves des autres pour voler leurs secrets les plus précieux.', '{"acteur": [{"nom": "Leonardo", "prenom": "DiCaprio", "dateNaissance": "11/11/1974", "nationalite": "américaine"}], "realisateur": [{"nom": "Christopher", "prenom": "Nolan", "dateNaissance": "30/07/1970", "nationalite": "britannique"}]}', '[{"id": 7, "etat": "Neuf", "disponible": true}, {"id": 8, "etat": "Bon", "disponible": true}, {"id": 9, "etat": "Abime", "disponible": true}]' ),
('Amélie Poulain', '2001-04-25', 'UGC Distribution', 'Comédie romantique', 1, 8, 'Français', 122, 'Amélie, une jeune femme imaginative, décide de rendre le monde meilleur pour les personnes qui l entourent.', '{"acteur": [{"nom": "Audrey", "prenom": "Tautou", "dateNaissance": "09/08/1976", "nationalite": "française"}], "realisateur": [{"nom": "Jean-Pierre", "prenom": "Jeunet", "dateNaissance": "03/09/1953", "nationalite": "française"}]}', '[{"id": 10, "etat": "Neuf", "disponible": true}, {"id": 11, "etat": "Bon", "disponible": true}, {"id": 12, "etat": "Abime", "disponible": true}]' );

INSERT INTO Musique ( titre, dateApparition, editeur, genre, codeClassification, dureeMaxPret, longueur, contributeur, exemplaires ) VALUES
('La La Land - Original Motion Picture Soundtrack', '2016-12-09', 'Interscope Records', 'Bande originale de film', 2, 14, 50, '{"compositeur": [{"nom": "Justin", "prenom": "Hurwitz", "dateNaissance": "22/01/1985", "nationalite": "américaine"}], "interprete": [{"nom": "Ryan", "prenom": "Gosling", "dateNaissance": "12/11/1980", "nationalite": "canadienne"}, {"nom": "Emma", "prenom": "Stone", "dateNaissance": "06/11/1988", "nationalite": "américaine"}]}', '[{"id": 4, "etat": "Neuf", "disponible": true}, {"id": 5, "etat": "Bon", "disponible": true}, {"id": 6, "etat": "Abime", "disponible": true}]' ),
('Édith Piaf - La vie en rose', '1947-06-12', 'Capitol Records', 'Chanson française', 3, 12, 35, '{"compositeur": [{"nom": "Édith", "prenom": "Piaf", "dateNaissance": "19/12/1915", "nationalite": "française"}], "interprete": [{"nom": "Édith", "prenom": "Piaf", "dateNaissance": "19/12/1915", "nationalite": "française"}]}', '[{"id": 7, "etat": "Neuf", "disponible": true}, {"id": 8, "etat": "Bon", "disponible": true}, {"id": 9, "etat": "Abime", "disponible": true}]' ),
('Daft Punk - Random Access Memories', '2013-05-17', 'Columbia Records', 'Électronique', 1, 10, 75, '{"compositeur": [{"nom": "Thomas", "prenom": "Bangalter", "dateNaissance": "03/01/1975", "nationalite": "française"}, {"nom": "Guy-Manuel", "prenom": "de Homem-Christo", "dateNaissance": "08/02/1974", "nationalite": "française"}], "interprete": [{"nom": "Daft Punk", "prenom": "", "dateNaissance": "", "nationalite": "française"}]}', '[{"id": 10, "etat": "Neuf", "disponible": true}, {"id": 11, "etat": "Bon", "disponible": true}, {"id": 12, "etat": "Abime", "disponible": true}]' );

INSERT INTO Utilisateur (login, password, prenom, nom, email, adresse) VALUES 
('utilisateur1', 'mdp123', 'Jean', 'Dupont','jean@example.com', '{"rue": "Rue de la Paix", "numero": 10, "codePostal": "75001", "ville": "Paris"}'),
('utilisateur2', 'mdp123', 'Fabrice', 'Durand','fabrice@example.com', '{"rue": "Rue de Clermont", "numero": 20, "codePostal": "30200", "ville": "Bagnols-sur-Cèze"}'),
('utilisateur3', 'mdp123', 'Marie', 'Martin','marie@example.com', '{"rue": "Rue de la République", "numero": 30, "codePostal": "13001", "ville": "Marseille"}'),
('utilisateur4', 'mdp123', 'Sophie', 'Bernard','sophie@example.com', '{"rue": "Rue de la Liberté", "numero": 40, "codePostal": "69001", "ville": "Lyon"}'),
('utilisateur5', 'mdp123', 'Pierre', 'Petit', 'pierre@example.com', '{"rue": "Rue de la Gare", "numero": 50, "codePostal": "59000", "ville": "Lille"}');

INSERT INTO Adherent (id, numeroTelephone, dateNaissance, statut, sanctions, prets) VALUES
(1, '0123456789', '2002-01-01', 'active', '[{"motif":"deterioration", "dateSanction":"2023-12-15", "dateFinSanction":"null", "montant":10, "paye":0}]','[{"duree": 20, "datePret": "2023-12-01","dateRetour": "2023-12-10", "etatRetour":"Bon", "id": 303, "exemplaireId": 5,"idRessource": 1, "idPersonnel": 1, "type": "Livre"}]'),
(2, '0456926843', '1995-01-01', 'active', '[{"motif":"deterioration", "dateSanction":"2023-11-12", "dateFinSanction":"null", "montant":10, "paye":1}]','[{"duree": 20, "datePret": "2023-12-01","dateRetour": "2023-12-10", "etatRetour":"Bon", "id": 304, "exemplaireId": 6,"idRessource": 1, "idPersonnel": 1, "type": "Livre"}]'),
(3, '0634434566', '2003-01-01', 'active', '[{"motif":"deterioration", "dateSanction":"2023-09-20", "dateFinSanction":"null", "montant":10, "paye":0}]','[{"duree": 20, "datePret": "2023-12-01","dateRetour": "2023-12-10", "etatRetour":"Bon", "id": 305, "exemplaireId": 7,"idRessource": 1, "idPersonnel": 1, "type": "Livre"}]');

INSERT INTO Personnel (id) VALUES
(2);

-- SELECT prenom, nom, email, A->>'rue' AS Rue, A->>'numero' AS Numero, A->>'codePostal' AS Code_Postal, A->>'ville' AS Ville 
-- FROM Utilisateur U, JSON_ARRAY_ELEMENT(U.Adresse) A;

-- SELECT u.nom, u.prenom, a.statut, s->>'motif' AS Motif, s->>'datePret' AS Date_Pret, s->>'dateRetour' AS Date_Retour
-- FROM Utilisateur u, Adherent a, JSON_ARRAY_ELEMENTS(a.Sanctions) s
-- WHERE u.id = a.id;

-- SELECT titre, dateApparition, editeur, genre, codeClassification, CAST(E->>'id' AS INTEGER) AS id_exemplaire, E->>'etat' AS etat_exemplaire, C->>'realisateur' AS Realisateur, C->>'acteur' AS Acteur, C->>'auteur' AS Auteur
-- FROM Ressource R, JSON_ARRAY_ELEMENTS(R.exemplaires) E, JSON_ARRAY_ELEMENTS(R.contributeur) C;
